# permissions for end users to view images.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-viewer-role
rules:
- apiGroups:
  - kupenstack.io
  resources:
  - images
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kupenstack.io
  resources:
  - images/status
  verbs:
  - get
